import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const sections = [
  { id: 'drugs', title: 'دارونامه', en: 'DRUG REFERENCE', desc: 'جست‌وجوی اطلاعات دارویی و منابع تخصصی', href: '/drugs' },
  { id: 'market', title: 'بازار تخصصی', en: 'PROFESSIONAL MARKET', desc: 'مواد، ابزار و منابع موردنیاز داروسازی', href: '/market' },
  { id: 'learn', title: 'آموزش', en: 'CONTINUING EDUCATION', desc: 'یادگیری پیوسته و مسیرهای حرفه‌ای', href: '/learn' },
  { id: 'compound', title: 'ساخت ترکیبات', en: 'COMPOUNDING DESK', desc: 'بررسی مرحله‌به‌مرحله ساخت داروهای ترکیبی', href: '/compounding' },
  { id: 'jobs', title: 'کار و شیفت', en: 'CAREER & SHIFTS', desc: 'فرصت‌های شغلی در جامعه داروسازی', href: '/careers' },
  { id: 'library', title: 'کتابخانه', en: 'KNOWLEDGE LIBRARY', desc: 'مقاله، کتاب و محتوای علمی', href: '/library' },
  { id: 'events', title: 'رویدادها', en: 'EVENTS & MEETINGS', desc: 'همایش‌ها، وبینارها و نشست‌های علمی', href: '/events' },
  { id: 'network', title: 'شبکه حرفه‌ای', en: 'PROFESSIONAL NETWORK', desc: 'ارتباط میان داروسازان و جامعه دانشگاهی', href: '/community' },
];

const routeTitles = {
  '/drugs': ['دارونامه', 'مرجع جست‌وجوی دارو', 'نام ژنریک، نام تجاری یا مادهٔ مؤثره را جست‌وجو کنید. اطلاعات این بخش پس از اتصال منبع دادهٔ تأییدشده نمایش داده می‌شود.'],
  '/market': ['بازار تخصصی', 'فروشگاه شکیب لرن', 'فهرست محصولات آموزشیِ قابل تهیه در فروشگاه، با قیمت و تصویر ثبت‌شده برای هر دوره.'],
  '/learn': ['آموزش حرفه‌ای', 'یادگیری پیوسته در داروسازی', 'فهرست دوره‌ها، معرفی و تصاویر موجود را همین‌جا ببینید؛ هر دوره فقط با اطلاعات منتشرشده و قابل انتقال نمایش داده می‌شود.'],
  '/compounding': ['میز ساخت ترکیبات', 'از جست‌وجوی فرمول تا فهرست مواد', 'نام محصول یا ترکیب را وارد کنید. نمایش فرمول فقط با منبع معتبر و قابل بررسی فعال می‌شود.'],
  '/careers': ['کار و شیفت', 'فرصت‌های حرفه‌ای داروسازی', 'آگهی‌های شغلی و شیفت‌های تأییدشده در این صفحه فهرست می‌شوند.'],
  '/library': ['کتابخانه', 'دانش برای مراجعهٔ دوباره', 'مقالات، کتاب‌ها و ویدیوهای معتبر پس از آماده‌سازی مخزن محتوا نمایش داده خواهند شد.'],
  '/events': ['رویدادها', 'تقویم جامعه داروسازی', 'نشست‌ها و کارگاه‌های ثبت‌شده به‌زودی در این بخش قابل مرور هستند.'],
  '/community': ['شبکه حرفه‌ای', 'جامعه‌ای برای هم‌آموزی', 'پروفایل‌های تأییدشده و ارتباطات دانشگاهی پس از فعال‌سازی ثبت‌نام در دسترس خواهند بود.'],
  '/download': ['دریافت اپلیکیشن', 'دانش داروسازی، همراه شما', 'نسخهٔ اندروید از همین سامانه دریافت می‌شود؛ وب‌اپ نیز روی همین نشانی نصب خواهد شد.'],
  '/about': ['دربارهٔ شکیب لرن', 'دانش تخصصی، در دسترس جامعهٔ داروسازی', 'شکیب لرن خدمات علمی، آموزشی و حرفه‌ای را در یک سامانهٔ مستقل گردآوری می‌کند.'],
  '/contact': ['ارتباط با ما', 'پیشنهاد یا پرسشی دارید؟', 'راه‌های ارتباطی رسمی پس از تأیید مالک پروژه در این صفحه ثبت خواهند شد.'],
  '/account': ['حساب کاربری', 'ورود به حساب حرفه‌ای', 'ورود و ثبت‌نام امن در صفحهٔ اختصاصی حساب انجام می‌شود.'],
  '/login': ['ورود به حساب', 'ورود به فضای حرفه‌ای', 'برای ورود به حساب خود، اطلاعات را در فرم امن وارد کنید.'],
  '/register': ['ساخت حساب', 'عضویت در جامعهٔ داروسازی', 'حساب حرفه‌ای خود را با اطلاعات واقعی ایجاد کنید.'],
  '/shortages': ['گزارش کمبود', 'وضعیت دسترسی به دارو را ثبت کنید', 'گزارش‌ها پس از بررسی داروخانه‌ها به مرجع اطلاع‌رسانی تبدیل می‌شوند.'],
  '/books': ['کتاب‌ها', 'کتابخانهٔ تخصصی', 'فهرست کتاب‌ها فقط پس از تأیید اطلاعات نشر منتشر می‌شود.'],
  '/articles': ['مقاله‌ها', 'خواندنی‌های علمی', 'مقاله‌های دارای منبع، نویسنده و تاریخ انتشار در این بخش قرار می‌گیرند.'],
  '/videos': ['ویدیوها', 'یادگیری دیداری', 'ویدیوهای آموزشیِ تأییدشده پس از اتصال کتابخانهٔ رسانه قابل مشاهده هستند.'],
  '/shifts': ['تبادل شیفت', 'شیفت مناسب خود را پیدا کنید', 'شیفت‌های ثبت‌شده همراه زمان، شهر و شرایط در این بخش نمایش داده می‌شوند.'],
  '/universities': ['دانشگاه‌ها', 'شبکهٔ دانشگاهی داروسازی', 'فهرست دانشگاه‌ها و گروه‌ها پس از ورود دادهٔ معتبر فعال می‌شود.'],
  '/exam': ['آزمون', 'تمرین و سنجش دانش', 'بانک سؤال و آزمون فقط با محتوای آموزشی مجاز و تأییدشده فعال خواهد شد.'],
  '/certificates': ['گواهی‌نامه‌ها', 'اعتبارسنجی دستاوردهای آموزشی', 'گواهی‌نامه‌های صادرشده با کد یکتا در این بخش قابل بررسی خواهند بود.'],
  '/applications': ['درخواست‌های من', 'پیگیری درخواست‌های حرفه‌ای', 'درخواست‌های شغلی و آموزشی ثبت‌شده در حساب کاربری شما نمایش داده می‌شوند.'],
  '/profile': ['پروفایل حرفه‌ای', 'معرفی مسیر حرفه‌ای شما', 'اطلاعات حرفه‌ای و مدارک پس از ورود و تأیید هویت مدیریت می‌شوند.'],
  '/dashboard': ['میز کار من', 'نمای کلی فعالیت‌های شما', 'سفارش، یادگیری، درخواست‌ها و گواهی‌نامه‌ها در یک نمای روشن گردآوری می‌شوند.'],
  '/orders': ['سفارش‌ها', 'پیگیری خریدهای شما', 'سفارش‌های ثبت‌شده در حساب کاربری نمایش داده می‌شوند.'],
  '/cart': ['سبد خرید', 'مرور اقلام انتخاب‌شده', 'سبد به حساب کاربری متصل است و پیش از پرداخت می‌توانید اقلام را بازبینی کنید.'],
  '/checkout': ['ثبت سفارش', 'اطلاعات ارسال و پرداخت', 'ثبت سفارش و پرداخت پس از اتصال سرویس‌های رسمی فروش فعال می‌شود.'],
  '/points': ['امتیاز و اعتبار', 'اعتبار حرفه‌ای شما', 'امتیازها فقط بر اساس فعالیت‌های ثبت‌شده و قابل بررسی محاسبه می‌شوند.'],
  '/notifications': ['اعلان‌ها', 'به‌روز با اتفاق‌های مهم', 'اعلان‌های مربوط به حساب، آموزش و سفارش در این بخش دیده می‌شوند.'],
  '/settings': ['تنظیمات', 'کنترل حساب و ترجیحات', 'تنظیمات حساب پس از ورود در این صفحه مدیریت می‌شوند.'],
  '/privacy': ['حریم خصوصی', 'داده‌های شما، با شفافیت', 'اطلاعات شخصی فقط برای ارائهٔ خدمات و بر اساس سیاست نهایی مالک سایت پردازش می‌شود.'],
  '/terms': ['قوانین استفاده', 'چارچوب استفاده از خدمات', 'متن حقوقی نهایی باید با تأیید مالک سایت و مشاور حقوقی منتشر شود.'],
  '/admin': ['مدیریت', 'ورود مدیر سامانه', 'این فضا در منوی عمومی قرار ندارد و تنها برای حساب مدیریتیِ تأییدشده قابل دسترسی است.'],
  '/search': ['جست‌وجو', 'جست‌وجو در شکیب لرن', 'دارو، خدمات و محتوای منتشرشده را از یک نقطه پیدا کنید.'],
  '/application': ['دریافت اپلیکیشن', 'دانش داروسازی، همراه شما', 'نسخهٔ اندروید و وب‌اپلیکیشن محلی شکیب لرن در این صفحه قرار دارند.'],
};

function Mark({ small = false }) { return <a className={`brand ${small ? 'brand-small' : ''}`} href="/" aria-label="شکیب لرن، صفحه نخست"><img src="/shakiblearn-logo.png" alt="" /><span><strong>شکیب لرن</strong><small>آموزش تخصصی داروسازی و فرمولاسیون</small></span></a>; }
function Arrow() { return null; }
let csrfToken = null;
async function api(path, options = {}) { const response=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.error||'ارتباط با سرویس انجام نشد.');return data; }
async function apiWrite(path, method, body) { if(!csrfToken){const session=await api('/api/auth/session');csrfToken=session.csrf;} if(!csrfToken)throw new Error('برای انجام این کار وارد حساب شوید.');return api(path,{method,headers:{'X-CSRF-Token':csrfToken},body:JSON.stringify(body)}); }
function cartRead(){try{return JSON.parse(localStorage.getItem('daro-cart')||'[]')}catch{return []}}
function cartWrite(items){localStorage.setItem('daro-cart',JSON.stringify(items));window.dispatchEvent(new Event('daro-cart-change'));}

function Header({ path, theme, onTheme }) {
  const [open, setOpen] = useState(false);
  const [cartCount, setCartCount] = useState(()=>cartRead().reduce((n,x)=>n+(Number(x.quantity)||0),0));
  React.useEffect(()=>{const sync=()=>setCartCount(cartRead().reduce((n,x)=>n+(Number(x.quantity)||0),0));window.addEventListener('daro-cart-change',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('daro-cart-change',sync);window.removeEventListener('storage',sync)}},[]);
  return <>
    <header className="header"><div className="wrap nav-row"><Mark /><button className="menu-toggle" aria-label={open ? 'بستن فهرست' : 'باز کردن فهرست'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? 'بستن' : 'منو'}</button><nav className={open ? 'nav open' : 'nav'}>{sections.slice(0, 6).map(s => <a className={path === s.href ? 'active' : ''} key={s.id} href={s.href} onClick={() => setOpen(false)}>{s.title}</a>)}<a className="mobile-download-link" href="/download" onClick={() => setOpen(false)}>دانلود اپلیکیشن</a><details className="services-menu"><summary>همهٔ خدمات</summary><div>{sections.slice(6).map(s => <a key={s.id} href={s.href}>{s.title}<Arrow /></a>)}<a href="/shortages">گزارش کمبود دارو<Arrow /></a><a href="/shifts">تبادل شیفت<Arrow /></a><a href="/universities">دانشگاه‌ها<Arrow /></a></div></details></nav><div className="nav-tools"><button className="theme-toggle" onClick={onTheme} aria-label={theme === 'dark' ? 'فعال کردن حالت روشن' : 'فعال کردن حالت تاریک'} title={theme === 'dark' ? 'حالت روشن' : 'حالت تاریک'}>{theme === 'dark' ? 'حالت روشن' : 'حالت تیره'}</button><a className="cart-link" href="/cart" aria-label={`سبد خرید، ${cartCount} قلم`}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M3 4h2l2.3 11.2a2 2 0 0 0 2 1.6h8.9a2 2 0 0 0 1.9-1.5L22 8H6"/><circle cx="10" cy="20" r="1.2"/><circle cx="18" cy="20" r="1.2"/></svg><span>{cartCount.toLocaleString('fa-IR')}</span><b>سبد</b></a><a className="download-cta" href="/download">دانلود اپلیکیشن</a><a className="login" href="/login">ورود</a></div></div></header>
  </>;
}

function SearchBox({ route = '/drugs', placeholder = 'نام دارو، مادهٔ مؤثره یا موضوع را بنویسید' }) {
  const [term, setTerm] = useState('');
  const [message, setMessage] = useState('');
  return <form className="searchbox" action="/search" method="get"><input name="q" aria-label="جست‌وجو" placeholder={placeholder} value={term} onChange={e => { setTerm(e.target.value); setMessage(''); }} /><button type="submit">جست‌وجو</button>{message && <span className="search-note" role="status">{message}</span>}</form>;
}

function ChemistryArt() {
  return <div className="art-stage"><img src="/media/shakib-workshop.jpg" alt="آماده‌سازی فرآوردهٔ ترکیبی در کارگاه داروسازی شکیب لرن" fetchPriority="high" /></div>;
}

function Home() {
  return <main>
    <section className="home-hero"><div className="wrap hero-grid"><div className="hero-copy"><div className="eyebrow"><span></span> سکوی تخصصی جامعهٔ داروسازی ایران</div><h1>دانشِ درست،<br /><em>در لحظهٔ نیاز.</em></h1><p className="hero-lead">از شناخت دارو تا یادگیری و کار حرفه‌ای؛ منابع و ابزارهای داروسازی را در یک مسیر روشن پیدا کنید.</p><SearchBox /><div className="quick-links"><span>ورود سریع</span><a href="/drugs">دارونامه</a><a href="/compounding">ساخت ترکیبات</a><a href="/learn">آموزش</a></div><a className="hero-download-cta" href="/download">دانلود اپلیکیشن</a></div><div className="hero-visual"><ChemistryArt /></div></div></section>
    <section className="service-index"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">میز کار شما</span><h2>از کجا شروع کنیم؟</h2></div><p>برای هر نیاز، یک مسیر مشخص.<br />بدون شلوغی، بدون جست‌وجوی اضافه.</p></div><div className="service-list">{sections.map((s, i) => <a href={s.href} className="service-row" key={s.id}><span className="service-no">۰{i + 1}</span><span className="service-name"><strong>{s.title}</strong><small>{s.en}</small></span><span className="service-desc">{s.desc}</span></a>)}</div></div></section>
    <section className="learning-feature"><div className="wrap feature-grid"><div className="feature-art"><img src="/media/clinical-learning.webp" alt="داروسازان در جلسهٔ بررسی بالینی و آموزشی" loading="lazy" /></div><div className="feature-copy"><div className="eyebrow">یادگیری حرفه‌ای</div><h2>دانش را به‌روز نگه دارید؛<br /><em>مسیرتان را خودتان بسازید.</em></h2><p>دوره، ویدیو، آزمون و گواهی‌نامه هرکدام مسیر روشن خود را دارند؛ از معرفی و برنامهٔ یادگیری تا پیگیری پیشرفت.</p><div className="feature-links"><a className="text-link" href="/learn">دوره‌های آموزشی <Arrow /></a><a className="text-link" href="/exam">آزمون و تمرین <Arrow /></a><a className="text-link" href="/certificates">اعتبار گواهی‌نامه <Arrow /></a></div></div></div></section>
    <section className="community-feature"><div className="wrap community-inner"><div><span className="eyebrow">جامعهٔ حرفه‌ای</span><h2>کار، رویداد و هم‌دانشگاهی‌ها<br />در دسترس شما.</h2><p>فرصت‌های کاری و شیفت، برنامه‌های علمی و شبکهٔ دانشگاهی هرکدام در مسیر خودشان قابل پیگیری‌اند.</p></div><div className="community-links"><a href="/careers"><span>۰۱</span><strong>استخدام</strong><small>فرصت‌های شغلی</small><Arrow /></a><a href="/shifts"><span>۰۲</span><strong>تبادل شیفت</strong><small>زمان و محل</small><Arrow /></a><a href="/events"><span>۰۳</span><strong>رویداد علمی</strong><small>وبینار و کارگاه</small><Arrow /></a><a href="/universities"><span>۰۴</span><strong>شبکه دانشگاهی</strong><small>هم‌ورودی‌ها</small><Arrow /></a></div></div></section>
    <section className="closing-band"><div className="wrap closing-inner"><div><span className="eyebrow">یک مرجع، چند مسیر</span><h2>برای زندگی حرفه‌ای<br />داروسازان.</h2></div><p>از دارونامه و ساخت ترکیبات تا آموزش، فروشگاه تخصصی و ارتباط حرفه‌ای؛ ابزارها با اولویت دسترسی آسان و دادهٔ معتبر کنار هم قرار می‌گیرند.</p><a href="/about" className="closing-cta">آشنایی با شکیب لرن</a></div></section>
  </main>;
}

function DirectoryPage({ path }) {
  const [active, setActive] = useState('همه');
  const info = routeTitles[path] || ['صفحه', 'به شکیب لرن خوش آمدید', ''];
  const isMarket = path === '/market';
  const isLearn = path === '/learn';
  const isJobs = path === '/careers';
  const isLibrary = ['/library', '/books', '/articles', '/videos'].includes(path);
  const filters = isMarket ? ['همه', 'مواد اولیه', 'تجهیزات', 'ظروف', 'کتاب'] : isLearn ? ['همه', 'دوره‌ها', 'ویدیوها', 'گواهی‌نامه'] : isJobs || path === '/shifts' ? ['همه', 'استخدام', 'شیفت'] : isLibrary ? ['همه', 'کتاب', 'مقاله', 'ویدیو'] : path === '/events' ? ['همه', 'وبینار', 'سمینار', 'ورکشاپ'] : path === '/community' || path === '/universities' ? ['همه', 'دانشجو', 'داروساز', 'استاد'] : ['همه', 'داروهای انسانی', 'مادهٔ مؤثره', 'گزارش کمبود'];
  if (path.startsWith('/admin')) return <AdminAccess path={path} />;
  if (path === '/search') return <SearchResults />;
  if (path === '/shortages') return <ShortageForm />;
  if (path === '/cart') return <CartPage />;
  if (path === '/checkout') return <CheckoutPage />;
  if (['/dashboard', '/profile', '/orders', '/applications', '/certificates', '/points', '/notifications', '/settings'].includes(path)) return <MemberArea path={path} info={info} />;
  return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a><span> / </span>{info[0]}</div><div className="page-intro"><div><div className="eyebrow"><span></span>{sections.find(s => s.href === path)?.en || 'SHAKIB LEARN'}</div><h1>{info[1]}</h1><p>{info[2]}</p></div></div>
    {(path === '/drugs' || path === '/compounding' || path === '/library') && <SearchBox route={path} placeholder={path === '/compounding' ? 'نام فرآورده یا ترکیب را جست‌وجو کنید' : path === '/library' ? 'جست‌وجوی عنوان، نویسنده یا موضوع' : 'نام ژنریک، نام تجاری یا مادهٔ مؤثره'} />}
    {path === '/compounding' && <CompoundingForm />}
    {['/download','/application'].includes(path) && <DownloadPanel />}
    {path === '/contact' && <ContactForm />}
    {path === '/about' && <AboutPanel />}
    {['/privacy', '/terms'].includes(path) && <AboutPanel legal={path === '/terms'} />}
    {['/drugs', '/market', '/learn', '/careers', '/shifts', '/library', '/books', '/articles', '/videos', '/events', '/community', '/universities', '/exam', '/certificates'].includes(path) && <>
      {isLearn && <div className="section-photo"><img src="/media/clinical-learning.webp" alt="نشست علمی داروسازی بالینی" loading="lazy" /><div><span>یادگیری ساختارمند</span><p>معرفی دوره، فصل‌ها، محتوای آموزشی، آزمون و گواهی‌نامه در همین مسیر کنار هم قرار می‌گیرند.</p><a href="/exam">رفتن به آزمون‌ها <Arrow /></a></div></div>}
      {path === '/events' && <div className="section-photo"><img src="/media/pharmacy-symposium.webp" alt="همایش علمی در حوزهٔ داروسازی" loading="lazy" /><div><span>نشست و گردهمایی</span><p>اطلاعات زمان، شیوهٔ برگزاری، ظرفیت و مدرس در صفحهٔ هر رویداد نمایش داده خواهد شد.</p><a href="/contact">درخواست ثبت رویداد <Arrow /></a></div></div>}
      {(!isMarket && (isLibrary || isJobs || path === '/drugs' || path === '/shifts' || path === '/community' || path === '/universities' || path === '/exam' || path === '/certificates')) && <div className="filter-tabs" role="tablist" aria-label="فیلتر بخش">{filters.map(x => <button key={x} className={active === x ? 'selected' : ''} onClick={() => setActive(x)} aria-selected={active === x}>{x}</button>)}</div>}
      {path === '/drugs' && <a className="subtle-action" href="/shortages">گزارش کمبود یا نبود دسترسی دارو <Arrow /></a>}
      {path === '/careers' && <a className="subtle-action" href="/account">ثبت فرصت شغلی <Arrow /></a>}
      {path === '/shifts' && <a className="subtle-action" href="/account">ثبت یا جابه‌جایی شیفت <Arrow /></a>}
      {path === '/library' && <div className="library-shortcuts"><a href="/books">کتاب‌ها <Arrow /></a><a href="/articles">مقاله‌ها <Arrow /></a><a href="/videos">ویدیوها <Arrow /></a></div>}
      <RecordsPanel path={path} category={active} suppressEmpty={isMarket} />
      {isMarket&&<ShopCoursesPanel />}
    </>}
  </div></main>;
}

function EmptyState({ title = 'محتوایی پیدا نشد', description }) { return <div className="empty-record"><div><b>{title}</b><p>{description}</p></div><span className="empty-state">فهرست آمادهٔ دریافت داده</span></div>; }

const resourceByPath={'/drugs':'drugs','/market':'products','/learn':'courses','/events':'events','/careers':'jobs','/shifts':'shifts','/library':'articles','/books':'books','/articles':'articles','/videos':'videos','/universities':'universities','/community':'universities','/certificates':'certificates'};
function RecordsPanel({path,category='همه',suppressEmpty=false}) {
  const kind=resourceByPath[path]; const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
  React.useEffect(()=>{let live=true;setLoading(true);api(`/api/public/${kind}`).then(x=>{if(live)setItems(x.items||[])}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[kind]);
  const filtered=items.filter(x=>(category==='همه'||!category||x.category===category||x.category.includes(category))&&(x.title+' '+x.summary+' '+x.category).toLocaleLowerCase('fa').includes(query.trim().toLocaleLowerCase('fa')));
  if(loading)return <div className="loading-line" role="status">در حال دریافت فهرست…</div>;
  if(error)return <EmptyState title="دریافت فهرست انجام نشد" description="ارتباط با پایگاه داده در دسترس نیست. سرویس محلی را با دستور راهنمای پروژه اجرا کنید." />;
  if(!filtered.length)return suppressEmpty?null:<EmptyState title="موردی برای نمایش ثبت نشده است" description="این فهرست فقط از داده‌های منتشرشده و تأییدشده ساخته می‌شود؛ رکورد آزمایشی یا محتوای بدون منبع نمایش داده نمی‌شود." />;
  return <><div className="directory-toolbar"><span>{filtered.length.toLocaleString('fa-IR')} مورد</span><input aria-label="جست‌وجو در فهرست" placeholder="جست‌وجو در همین بخش" value={query} onChange={e=>setQuery(e.target.value)} /></div><div className={kind==='products'?'record-list product-list':kind==='courses'?'record-list course-list':'record-list'}>{filtered.map(r=><RecordItem key={r.id} record={r} kind={kind}/>)}</div></>;
}
function ShopCoursesPanel(){
  const [items,setItems]=useState([]);const [query,setQuery]=useState('');const [category,setCategory]=useState('همه');const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  React.useEffect(()=>{let live=true;api('/api/public/courses').then(result=>{if(live)setItems((result.items||[]).filter(course=>course.body?.shopListed))}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
  const categories=['همه',...new Set(items.map(course=>course.category).filter(Boolean))];
  const filtered=items.filter(course=>(category==='همه'||course.category===category)&&(course.title+' '+course.summary+' '+course.category).toLocaleLowerCase('fa').includes(query.trim().toLocaleLowerCase('fa')));
  return <section className="store-education" aria-labelledby="store-education-title"><div className="store-education-heading"><div><span className="eyebrow">فروشگاه رسمی شکیب لرن</span><h2 id="store-education-title">دوره‌های قابل تهیه</h2><p>این فهرست از دوره‌هایی ساخته شده که اکنون در فروشگاه شکیب لرن عرضه شده‌اند؛ عنوان، تصویر و قیمت به‌صورت محلی نگهداری می‌شوند.</p></div><span className="store-count">{loading?'…':filtered.length.toLocaleString('fa-IR')} دوره</span></div>{!loading&&!error&&items.length>0&&<><div className="directory-toolbar"><span>جست‌وجو در فروشگاه</span><input aria-label="جست‌وجو در دوره‌های فروشگاه" placeholder="نام دوره را جست‌وجو کنید" value={query} onChange={e=>setQuery(e.target.value)} /></div><div className="filter-tabs store-filters" role="tablist" aria-label="دسته‌بندی دوره‌های فروشگاه">{categories.map(value=><button key={value} className={category===value?'selected':''} onClick={()=>setCategory(value)} aria-selected={category===value}>{value}</button>)}</div></>}{error?<EmptyState title="دریافت کاتالوگ ممکن نشد" description="فهرست محلی دوره‌ها در حال حاضر در دسترس نیست."/>:loading?<div className="loading-line" role="status">در حال دریافت دوره‌ها…</div>:!filtered.length?<EmptyState title="دوره‌ای مطابق جست‌وجو پیدا نشد" description="عبارت یا دستهٔ دیگری را انتخاب کنید."/>:<div className="record-list course-list storefront-list">{filtered.map(course=><RecordItem key={course.id} record={course} kind="courses"/>)}</div>}<p className="store-payment-note">درخواست ثبت‌نام در این نسخه در سامانهٔ محلی ثبت می‌شود؛ پرداخت آنلاین تا اتصال درگاه فعال نیست.</p></section>;
}
function RecordAction({record,kind}){const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const config={jobs:['application','ارسال درخواست شغلی'],shifts:['shift','درخواست این شیفت'],events:['event-registration','ثبت‌نام در رویداد'],courses:['course-enrollment','درخواست ثبت‌نام']}[kind];if(!config)return null;return <div className="record-action"><button disabled={busy} onClick={async()=>{setBusy(true);try{const result=await apiWrite(`/api/submissions/${config[0]}`,'POST',{recordId:record.id,slug:record.slug,title:record.title});setMessage(`${result.message} · کد پیگیری ${result.id.toLocaleString('fa-IR')}`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}}>{busy?'در حال ارسال…':config[1]}</button>{message&&<small role="status">{message}</small>}{kind==='courses'&&!message&&<small>درخواست در همین سامانه ذخیره می‌شود؛ پرداخت برخط هنوز فعال نیست.</small>}</div>}
function coursePriceLabel(body={}) {
  const range=body.priceRangeToman;
  if(range&&Number.isFinite(range.min)&&Number.isFinite(range.max)&&range.max>range.min) return `از ${range.min.toLocaleString('fa-IR')} تا ${range.max.toLocaleString('fa-IR')} تومان`;
  return body.priceToman!=null?`${Number(body.priceToman).toLocaleString('fa-IR')} تومان`:'قیمت اعلام نشده';
}

function RecordItem({record,kind}) {
  const [added,setAdded]=useState(false);
  const href=kind==='drugs'?`/drug/${encodeURIComponent(record.slug)}`:kind==='products'?`/product/${encodeURIComponent(record.slug)}`:kind==='courses'?`/course/${encodeURIComponent(record.slug)}`:kind==='events'?`/event/${encodeURIComponent(record.slug)}`:`/${kind}/${encodeURIComponent(record.slug)}`;
  const add=()=>{const cart=cartRead();const found=cart.find(x=>x.id===record.id);if(found)found.quantity=Math.min(found.quantity+1,99);else cart.push({id:record.id,slug:record.slug,quantity:1});cartWrite(cart);setAdded(true)};
  return <article className="record-item">{record.imageUrl&&<img src={record.imageUrl} alt={record.title} loading="lazy"/>}<div className="record-meta">{record.category||kind}{record.sourceUrl&&<a href={record.sourceUrl} target="_blank" rel="noreferrer">منبع رسمی</a>}</div><a className="record-title" href={href}>{record.title}</a>{record.summary&&<p>{record.summary}</p>}
    {kind==='courses'&&<div className="course-external-purchase"><strong>{coursePriceLabel(record.body)}</strong><span>قیمت ثبت‌شده در کاتالوگ</span></div>}
    {kind==='products'&&<div className="product-buy"><strong>{record.price?.toLocaleString('fa-IR')} تومان</strong><span>{record.stock>0?'موجود':'ناموجود'}</span><button disabled={!record.stock} onClick={add}>{added?'به سبد اضافه شد':'افزودن به سبد'}</button></div>}<RecordAction record={record} kind={kind}/></article>;
}

function SearchResults() { const q = new URLSearchParams(window.location.search).get('q')?.trim() || ''; const matches = sections.filter(s => (s.title + ' ' + s.desc).includes(q)); return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / جست‌وجو</div><div className="page-intro"><div><div className="eyebrow"><span></span> جست‌وجوی سراسری</div><h1>{q ? `نتایج برای «${q}»` : 'جست‌وجو در شکیب لرن'}</h1><p>بخش‌های سایت و محتوای منتشرشده را از یک نقطه پیدا کنید.</p></div></div><SearchBox placeholder="نام دارو، آموزش، محصول یا موضوع" />{!q ? <EmptyState title="عبارتی وارد کنید" description="برای جست‌وجو، نام دارو، مادهٔ مؤثره، دوره یا موضوع موردنظرتان را بنویسید." /> : matches.length ? <div className="search-results">{matches.map(s => <a key={s.id} href={s.href}><span>{s.en}</span><strong>{s.title}</strong><small>{s.desc}</small><Arrow /></a>)}</div> : <EmptyState title="موردی پیدا نشد" description="در حال حاضر محتوای منتشرشده‌ای با این عبارت در سامانه وجود ندارد." />}</div></main>; }

function ShortageForm() { const [message,setMessage] = useState('');const [busy,setBusy]=useState(false); return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / <a href="/drugs">دارونامه</a> / گزارش کمبود</div><div className="page-intro"><div><div className="eyebrow"><span></span> گزارش دسترسی</div><h1>گزارش کمبود دارو</h1><p>گزارش داروخانه پس از ثبت در صف بررسی مدیر قرار می‌گیرد و مستقیم به‌عنوان کمبود عمومی منتشر نمی‌شود.</p></div><div className="page-mark">!</div></div><form className="workflow-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const b=Object.fromEntries(new FormData(form));setBusy(true);try{const r=await apiWrite('/api/submissions/shortage','POST',b);setMessage(`${r.message} کد پیگیری: ${r.id.toLocaleString('fa-IR')}`);form.reset()}catch(err){setMessage(err.message)}finally{setBusy(false)}}}><label>نام ژنریک یا تجاری دارو<input name="drug" required placeholder="نام دارو" /></label><label>شهر<input name="city" required placeholder="شهر" /></label><label>وضعیت دسترسی<select name="availability" defaultValue=""><option value="" disabled>انتخاب کنید</option><option>موجود نیست</option><option>دسترسی محدود</option><option>موجود اما کمیاب</option></select></label><label>توضیحات<textarea name="details" rows="3" placeholder="اطلاعات تکمیلی (اختیاری)" /></label><button type="submit" disabled={busy}>{busy?'در حال ثبت…':'ثبت گزارش برای بررسی'}</button>{message && <p role="status" className="form-notice">{message}</p>}</form><div className="medical-notice">گزارش کمبود جایگزین راهنمای درمانی یا مشاورهٔ داروساز نیست.</div></div></main>; }

function CartPage() {
  const [items,setItems]=useState(cartRead());const [records,setRecords]=useState([]);const [message,setMessage]=useState('');
  React.useEffect(()=>{let alive=true;Promise.all(items.map(async item=>{const r=await api(`/api/public/products/${encodeURIComponent(item.slug)}`);return {...r,quantity:item.quantity}})).then(list=>alive&&setRecords(list)).catch(e=>alive&&setMessage(e.message));return()=>{alive=false}},[items]);
  const remove=id=>{const next=items.filter(x=>x.id!==id);setItems(next);cartWrite(next)};const quantity=(id,value)=>{const next=items.map(x=>x.id===id?{...x,quantity:Math.max(1,Math.min(99,Number(value)||1))}:x);setItems(next);cartWrite(next)};const total=records.reduce((n,x)=>n+(x.price||0)*x.quantity,0);
  return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / سبد خرید</div><div className="page-intro"><div><div className="eyebrow"><span></span> سفارش شما</div><h1>سبد خرید</h1><p>موجودی و قیمت از فهرست منتشرشده خوانده می‌شود و هنگام ثبت سفارش دوباره در سرور بررسی خواهد شد.</p></div></div>{!items.length?<EmptyState title="سبد خرید شما خالی است" description="از بازار تخصصی یک کالای منتشرشده انتخاب کنید؛ هیچ کالای نمایشی داخل سبد از پیش قرار داده نشده است."/>:<><div className="cart-lines">{records.map(p=><div className="cart-line" key={p.id}><div><strong>{p.title}</strong><small>{p.price.toLocaleString('fa-IR')} تومان · موجودی {p.stock.toLocaleString('fa-IR')}</small></div><label>تعداد<input type="number" min="1" max={p.stock} value={p.quantity} onChange={e=>quantity(p.id,e.target.value)}/></label><strong>{(p.price*p.quantity).toLocaleString('fa-IR')} تومان</strong><button onClick={()=>remove(p.id)} aria-label={`حذف ${p.title}`}>حذف</button></div>)}</div><div className="cart-total"><span>جمع کالاها</span><strong>{total.toLocaleString('fa-IR')} تومان</strong><a href="/checkout">ادامه برای ثبت سفارش</a></div></>}{message&&<p role="status">{message}</p>}<a className="text-link" href="/market">ادامهٔ خرید</a></div></main>;
}

function CheckoutPage() {
  const [items]=useState(cartRead());const [form,setForm]=useState({recipient:'',phone:'',city:'',address:''});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');try{const result=await apiWrite('/api/orders','POST',{items,...form});cartWrite([]);setMessage(`سفارش شمارهٔ ${result.id.toLocaleString('fa-IR')} ثبت شد و در وضعیت «در انتظار پرداخت» است. ${result.payment.message}`)}catch(err){setMessage(err.message)}finally{setBusy(false)}};
  return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / <a href="/cart">سبد خرید</a> / ثبت سفارش</div><div className="page-intro"><div><div className="eyebrow"><span></span> تکمیل سفارش</div><h1>اطلاعات ارسال</h1><p>پرداخت تنها پس از تأیید نهایی درگاه، به‌عنوان پرداخت‌شده ثبت خواهد شد.</p></div></div>{items.length?<form className="workflow-form" onSubmit={submit}><label>نام گیرنده<input required value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})}/></label><label>شماره تماس<input required inputMode="tel" pattern="[0-9+() -]{8,20}" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>شهر<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>نشانی کامل<textarea rows="3" required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><button disabled={busy}>{busy?'در حال ثبت…':'ثبت سفارش و ادامه'}</button>{message&&<p role="status" className="form-notice">{message}</p>}</form>:<><EmptyState title="هنوز سفارشی برای پرداخت ندارید" description="سبد خرید خالی است. ابتدا کالای منتشرشده‌ای را به سبد اضافه کنید."/><a className="text-link" href="/market">رفتن به بازار <Arrow /></a></>}</div></main>;
}

function MemberArea({ path, info }) {
  const [user,setUser]=useState(null);const [orders,setOrders]=useState([]);const [submissions,setSubmissions]=useState([]);const [profile,setProfile]=useState({city:'',university:'',entryYear:'',specialty:'',bio:'',publicDirectory:false});const [message,setMessage]=useState('');
  React.useEffect(()=>{let active=true;api('/api/auth/session').then(async s=>{csrfToken=s.csrf;if(!active)return;setUser(s.user);if(s.user&&path==='/orders'){const o=await api('/api/orders');if(active)setOrders(o.items||[])}if(s.user&&path==='/profile'){const p=await api('/api/profile');if(active&&p.profile)setProfile(p.profile)}if(s.user&&path==='/applications'){const r=await api('/api/user/submissions');if(active)setSubmissions(r.items.filter(x=>['application','course-enrollment'].includes(x.kind)))}}).catch(e=>active&&setMessage(e.message));return()=>{active=false}},[path]);
  const saveProfile=async e=>{e.preventDefault();try{await apiWrite('/api/profile','PUT',profile);setMessage('پروفایل ذخیره شد.')}catch(e){setMessage(e.message)}};
}

function AdminAccess({path='/admin'}) {
  const [session,setSession]=useState(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  React.useEffect(()=>{api('/api/auth/session').then(x=>{csrfToken=x.csrf;setSession(x.user)}).catch(()=>setNotice('سرویس مدیریت در دسترس نیست.'))},[]);
  const login=async e=>{e.preventDefault();setBusy(true);setNotice('');try{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});csrfToken=result.csrf;if(result.user.role!=='admin'){setNotice('این حساب دسترسی مدیریتی ندارد.');await apiWrite('/api/auth/logout','POST',{});csrfToken=null;return}setSession(result.user)}catch(error){setNotice(error.message)}finally{setBusy(false)}};
  if(session?.role==='admin')return <AdminPanel path={path} user={session}/>;
  return <main className="inner-page admin-entry"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / فضای مدیریت</div><section className="admin-card"><span className="eyebrow">محدودهٔ خصوصی</span><h1>ورود مدیر سامانه</h1><p>این صفحه پیوند عمومی ندارد. فقط حسابی که مدیر اصلی از طریق دستور راه‌اندازی ساخته، مجاز است.</p><form onSubmit={login}><label>ایمیل مدیریتی<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" /></label><label>گذرواژه<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" /></label><button disabled={busy}>{busy?'در حال بررسی…':'ورود امن'}</button>{notice&&<p role="status">{notice}</p>}</form></section></div></main>;
}

const adminKinds={drugs:'داروها',compounds:'فرمول‌های ترکیبی',products:'محصولات',courses:'دوره‌ها',events:'رویدادها',articles:'مقاله‌ها',books:'کتاب‌ها',videos:'ویدیوها',jobs:'استخدام',shifts:'شیفت‌ها',universities:'دانشگاه‌ها',certificates:'گواهی‌نامه‌ها',pages:'صفحات',downloads:'فایل‌ها'};
function AdminPanel({path,user}) {
  const tab=path.split('/')[2]||'overview';const [importKind,setImportKind]=useState('drugs');const kind=adminKinds[tab]?tab:(tab==='seo'?'pages':tab==='import'?importKind:tab==='products'?'products':tab==='content'?'articles':'drugs');const [stats,setStats]=useState(null);const [records,setRecords]=useState([]);const [users,setUsers]=useState([]);const [orders,setOrders]=useState([]);const [submissions,setSubmissions]=useState([]);const [integrations,setIntegrations]=useState(null);const [message,setMessage]=useState('');const [editing,setEditing]=useState(null);const [importText,setImportText]=useState('');const [busy,setBusy]=useState(false);
  const load=async()=>{try{const s=await api('/api/admin/stats');setStats(s);if(tab==='users'){setUsers((await api('/api/admin/users')).items)}else if(tab==='orders'){setOrders((await api('/api/admin/orders')).items)}else if(tab==='submissions'){setSubmissions((await api('/api/admin/submissions')).items)}else if(tab==='integrations'){setIntegrations(await api('/api/admin/integrations'))}else if(adminKinds[kind]){setRecords((await api(`/api/admin/records/${kind}`)).items)}}catch(e){setMessage(e.message)}};
  React.useEffect(()=>{load()},[path]);
  const blank=()=>setEditing({title:'',slug:'',summary:'',sourceUrl:'',imageUrl:'',category:'',status:'draft',price:'',stock:'',body:'{}'});
  const save=async e=>{e.preventDefault();setBusy(true);setMessage('');try{const body={...editing,price:editing.price===''?null:Number(editing.price),stock:editing.stock===''?null:Number(editing.stock),body:JSON.parse(editing.body||'{}')};const result=editing.id?await apiWrite(`/api/admin/records/${kind}/${editing.id}`,'PUT',body):await apiWrite(`/api/admin/records/${kind}`,'POST',body);setMessage(editing.id?'تغییرات ذخیره شد.':'رکورد ساخته شد.');setEditing(null);await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
  const remove=async record=>{if(!window.confirm(`«${record.title}» حذف شود؟`))return;try{await apiWrite(`/api/admin/records/${kind}/${record.id}`,'DELETE',{});setMessage('رکورد حذف شد.');await load()}catch(e){setMessage(e.message)}};
  const importCsv=async()=>{setBusy(true);try{const result=await apiWrite(`/api/admin/import/${kind}`,'POST',{csv:importText});setMessage(`${result.imported.toLocaleString('fa-IR')} ردیف وارد شد.`);setImportText('');await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
  const verify=async person=>{try{await apiWrite(`/api/admin/users/${person.id}/verify`,'PATCH',{verified:!person.verified});await load()}catch(e){setMessage(e.message)}};
  const review=async(item,status)=>{try{await apiWrite(`/api/admin/submissions/${item.id}/status`,'PATCH',{status});await load()}catch(e){setMessage(e.message)}};
  const nav=[['/admin','نمای کلی'],...Object.entries(adminKinds).map(([k,v])=>[`/admin/${k}`,v]),['/admin/seo','SEO و صفحات'],['/admin/users','کاربران و تأیید'],['/admin/orders','سفارش‌ها و پرداخت'],['/admin/submissions','درخواست‌های بررسی'],['/admin/import','ورود اطلاعات'],['/admin/integrations','اتصال‌ها']];
  return <main className="admin-shell"><aside className="admin-sidebar"><a className="admin-brand" href="/admin">شکیب لرن <small>مدیریت محتوا</small></a>{nav.map(([href,label])=><a key={href} className={(path===href||(tab==='overview'&&href==='/admin'))?'current':''} href={href}>{label}</a>)}<a href="/" className="admin-exit">بازگشت به سایت</a></aside><section className="admin-content"><div className="admin-top"><div><span>مدیر سامانه</span><strong>{user.name}</strong></div><h1>{tab==='overview'?'نمای کلی':tab==='users'?'کاربران و تأیید':tab==='orders'?'سفارش‌ها و پرداخت':tab==='import'?'ورود اطلاعات':tab==='submissions'?'درخواست‌های بررسی':tab==='integrations'?'وضعیت اتصال‌ها':tab==='seo'?'SEO و صفحات':adminKinds[kind]||'مدیریت'}</h1></div>{message&&<p className="admin-message" role="status">{message}</p>}
    {(tab==='overview'||tab==='analytics')&&<>{stats&&<div className="stat-strip">{[['کاربران',stats.users],['سفارش‌ها',stats.orders],['درآمد پرداخت‌شده',`${stats.paidRevenue.toLocaleString('fa-IR')} تومان`],['داروها',stats.records.drugs||0],['محصولات',stats.records.products||0],['درخواست‌های بررسی',stats.pendingSubmissions||0]].map(([label,value])=><article key={label}><span>{label}</span><strong>{Number.isFinite(value)?value.toLocaleString('fa-IR'):value}</strong></article>)}</div>}<p className="admin-caption">آمار از پایگاه‌داده خوانده می‌شود؛ موردی که هنوز ثبت نشده، صفر نشان داده می‌شود. درآمد فقط تراکنش تأییدشده را می‌شمارد.</p></>}
    {tab==='users'&&<div className="admin-table-wrap"><table><thead><tr><th>نام</th><th>ایمیل</th><th>نقش</th><th>تأیید</th><th>عملیات</th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td>{x.role}</td><td>{x.verified?'تأییدشده':'بررسی‌نشده'}</td><td><button onClick={()=>verify(x)}>{x.verified?'لغو تأیید':'تأیید کاربر'}</button></td></tr>)}</tbody></table>{!users.length&&<EmptyState title="کاربری ثبت نشده است" description="پس از ثبت‌نام اعضا، مدیریت هویت و تأیید مدارک از این جدول انجام می‌شود."/>}</div>}
    {tab==='orders'&&<div className="admin-table-wrap"><table><thead><tr><th>شماره</th><th>گیرنده / شهر</th><th>شناسه کاربر</th><th>وضعیت</th><th>مبلغ</th><th>تاریخ</th><th>عملیات</th></tr></thead><tbody>{orders.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.shipping?.recipient} · {x.shipping?.city}</td><td>{x.userId}</td><td>{x.status==='pending_payment'?'در انتظار پرداخت':x.status}</td><td>{x.total.toLocaleString('fa-IR')} تومان</td><td>{new Date(x.createdAt).toLocaleDateString('fa-IR')}</td><td><button onClick={async()=>{if(x.status==='pending_payment'){setMessage('پرداخت تأییدشده از درگاه در دسترس نیست؛ این سفارش را به‌عنوان پرداخت‌شده علامت نزنید.');return}try{await apiWrite('/api/admin/orders/status','PATCH',{id:x.id,status:x.status==='processing'?'shipped':'processing'});await load()}catch(e){setMessage(e.message)}}}>{x.status==='processing'?'علامت ارسال':'پردازش سفارش'}</button></td></tr>)}</tbody></table>{!orders.length&&<EmptyState title="سفارشی ثبت نشده است" description="سفارش‌های کاربران پس از ثبت در این جدول ظاهر می‌شوند."/>}</div>}
    {tab==='submissions'&&<div className="admin-table-wrap"><table><thead><tr><th>شناسه</th><th>نوع</th><th>دادهٔ ثبت‌شده</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{submissions.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.kind}</td><td>{Object.values(x.data).filter(v=>typeof v==='string').join(' · ').slice(0,160)}</td><td>{x.status}</td><td><button onClick={()=>review(x,'reviewing')}>در حال بررسی</button><button onClick={()=>review(x,x.kind==='contact'?'resolved':'approved')}>تکمیل</button><button className="quiet-button" onClick={()=>review(x,'rejected')}>رد</button></td></tr>)}</tbody></table>{!submissions.length&&<EmptyState title="درخواستی برای بررسی نیست" description="گزارش‌های کمبود، تماس و درخواست‌های کاربران اینجا در صف مدیریت قرار می‌گیرند."/>}</div>}
    {tab==='integrations'&&<div className="integration-grid">{integrations&&Object.entries({analytics:'Google Analytics',searchConsole:'Search Console',payment:'درگاه زرین‌پال',sms:'پیامک',email:'ایمیل',drugSource:'منبع اطلاعات دارویی',marketplace:'ترب / بازار'}).map(([key,label])=><article key={key}><strong>{label}</strong><span className={integrations[key]?'connected':'not-connected'}>{integrations[key]?'پیکربندی شده':'پیکربندی نشده'}</span></article>)}<p>کلیدها فقط از متغیرهای محیطی سرور خوانده می‌شوند و هرگز در مرورگر یا پایگاه‌داده نمایش داده نمی‌شوند. پس از ثبت مقادیر در فایل محیطی امن، سرویس مربوطه را راه‌اندازی مجدد کنید.</p></div>}
    {tab==='seo'&&<div className="admin-caption">عنوان و توضیح صفحه را در فیلدهای SEO داخل دادهٔ تکمیلی JSON هر صفحه ذخیره کنید. Sitemap عمومی مسیرهای ایستا را پوشش می‌دهد. قبل از انتشار دامنه، URL نهایی پروژه را در sitemap و متغیر PUBLIC_ORIGIN تنظیم کنید.</div>}
    {tab==='import'&&<section className="admin-import"><label>نوع اطلاعات<select value={kind} onChange={e=>setImportKind(e.target.value)}>{Object.entries(adminKinds).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>فایل CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f)setImportText(await f.text())}}/></label><textarea rows="10" value={importText} onChange={e=>setImportText(e.target.value)} placeholder={'title,slug,summary,sourceUrl,status\nعنوان,slug,توضیح,https://...,draft'} /><p>تا ۱۰۰۰ ردیف در هر نوبت. ایمپورت تراکنشی است؛ در صورت خطا هیچ ردیفی از فایل ثبت نمی‌شود. محتوای علمی بدون منبع با وضعیت منتشرشده پذیرفته نمی‌شود.</p><button disabled={!importText||busy} onClick={importCsv}>اعتبارسنجی و ورود CSV</button></section>}
    {adminKinds[tab]&&<><div className="admin-actions"><button onClick={blank}>افزودن رکورد</button><a href="/admin/import">ورود CSV</a></div>{editing&&<form className="admin-editor" onSubmit={save}><label>عنوان<input required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>شناسه URL<input required dir="ltr" value={editing.slug} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label><label>دسته‌بندی<input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label>منبع معتبر<input dir="ltr" type="url" value={editing.sourceUrl} onChange={e=>setEditing({...editing,sourceUrl:e.target.value})}/></label><label>خلاصه<textarea value={editing.summary} onChange={e=>setEditing({...editing,summary:e.target.value})}/></label><label>نشانی تصویر<input dir="ltr" value={editing.imageUrl} onChange={e=>setEditing({...editing,imageUrl:e.target.value})}/></label>{kind==='products'&&<><label>قیمت (تومان)<input type="number" min="0" value={editing.price} onChange={e=>setEditing({...editing,price:e.target.value})}/></label><label>موجودی<input type="number" min="0" value={editing.stock} onChange={e=>setEditing({...editing,stock:e.target.value})}/></label></>}<label>وضعیت<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="draft">پیش‌نویس</option><option value="published">انتشار</option></select></label><label>دادهٔ تکمیلی JSON<textarea dir="ltr" value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></label><div><button disabled={busy}>{busy?'ذخیره…':'ذخیره رکورد'}</button><button type="button" className="quiet-button" onClick={()=>setEditing(null)}>انصراف</button></div></form>}<div className="admin-table-wrap"><table><thead><tr><th>عنوان</th><th>شناسه</th><th>دسته</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.title}</td><td dir="ltr">{r.slug}</td><td>{r.category}</td><td>{r.status==='published'?'منتشرشده':'پیش‌نویس'}</td><td><button onClick={()=>setEditing({...r,price:r.price??'',stock:r.stock??'',body:JSON.stringify(r.body,null,2)})}>ویرایش</button> <button className="quiet-button" onClick={()=>remove(r)}>حذف</button></td></tr>)}</tbody></table>{!records.length&&<EmptyState title="رکوردی در این بخش نیست" description="رکورد تازه بسازید یا از فایل CSV وارد کنید؛ تا آن زمان دادهٔ نمونه‌ای نمایش داده نمی‌شود."/>}</div></>}
    </section></main>;
}

function CompoundingForm() {
  const [name,setName]=useState('');const [results,setResults]=useState([]);const [products,setProducts]=useState([]);const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
  const submit=async e=>{e.preventDefault();if(!name.trim()){setMessage('نام فرآورده را وارد کنید.');return;}setLoading(true);setMessage('');try{const data=await api('/api/public/compounds');const matches=(data.items||[]).filter(x=>(x.title+' '+x.summary+' '+JSON.stringify(x.body)).toLocaleLowerCase('fa').includes(name.trim().toLocaleLowerCase('fa')));setResults(matches);if(matches.length){const p=await api('/api/public/products');setProducts(p.items||[])}else setMessage('فرمول تأییدشده‌ای با این عبارت در پایگاه فعلی ثبت نشده است.')}catch(err){setMessage(err.message)}finally{setLoading(false)}};
  const addRelated=compound=>{const ids=compound.body?.productIds||[];const available=products.filter(p=>ids.includes(p.id)||ids.includes(p.slug));if(!available.length){setMessage('برای این فرمول، کالای منتشرشده‌ای به فروشگاه متصل نیست.');return;}const cart=cartRead();for(const product of available){const entry=cart.find(x=>x.id===product.id);if(entry)entry.quantity=Math.min(99,entry.quantity+1);else cart.push({id:product.id,slug:product.slug,quantity:1});}cartWrite(cart);setMessage(`${available.length.toLocaleString('fa-IR')} قلم به سبد اضافه شد.`)};
  return <div className="compound-workspace"><form className="compound-form" onSubmit={submit}><label htmlFor="compound">نام فرآورده یا ترکیب موردنظر</label><div><input id="compound" value={name} onChange={e=>setName(e.target.value)} placeholder="جست‌وجو میان فرمول‌های دارای منبع" /><button disabled={loading}>{loading?'در حال بررسی…':<>بررسی منابع <Arrow /></>}</button></div><small>فقط فرمول تأییدشده با منبع قابل مشاهده است؛ پیشنهاد فرمول تولید نمی‌شود.</small>{message&&<p role="status">{message}</p>}</form>{results.map(item=><article className="formula-result" key={item.id}><div className="record-meta">فرمول منبع‌دار · {item.category||'ساخت ترکیبات'}<a href={item.sourceUrl} target="_blank" rel="noreferrer">مشاهدهٔ منبع <Arrow /></a></div><h2>{item.title}</h2>{item.summary&&<p>{item.summary}</p>}<div className="formula-columns"><div><b>مواد ثبت‌شده</b><ul>{(item.body?.materials||[]).map((x,i)=><li key={i}>{typeof x==='string'?x:x.name}</li>)}</ul></div><div><b>ابزار و اقلام</b><ul>{(item.body?.equipment||[]).map((x,i)=><li key={i}>{typeof x==='string'?x:x.name}</li>)}</ul></div></div>{(item.body?.productIds||[]).length>0&&<button className="outline-action" onClick={()=>addRelated(item)}>افزودن اقلام متصل به فروشگاه به سبد</button>}</article>)}</div>;
}
function DownloadPanel() {
  const [install,setInstall]=useState(null);const [notice,setNotice]=useState('');
  React.useEffect(()=>{const handler=e=>{e.preventDefault();setInstall(e)};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler)},[]);
  const prompt=async()=>{if(!install)return;await install.prompt();setNotice('درخواست نصب به دستگاه فرستاده شد.');setInstall(null)};
  return <div className="download-grid"><article className="download-app-card"><span>اپلیکیشن اندروید</span><h2>شکیب لرن را روی گوشی نصب کنید</h2><p>بستهٔ نصب همراه این نسخه است و مستقیماً از همین دامنه دریافت می‌شود.</p><a className="button-link" href="/downloads/shakiblearn.apk" download>دانلود اپلیکیشن اندروید</a><p className="install-hint">حجم فایل: ۲۵٫۴ مگابایت · فایل روی همین سایت میزبانی می‌شود.</p></article><article className="download-web-card"><span>وب‌اپلیکیشن</span><h2>بدون نصب، در مرورگر استفاده کنید</h2><p>همین سامانه را به صفحهٔ اصلی گوشی یا رایانه اضافه کنید؛ برای استفاده نیازی به باز کردن سایت دیگری نیست.</p>{install&&<button className="install-local" onClick={prompt}>نصب وب‌اپلیکیشن</button>}{notice&&<p role="status">{notice}</p>}<a className="button-link" href="/">ورود به وب‌اپلیکیشن</a></article></div>;
}
function ContactForm() { const [message,setMessage] = useState(''); const [busy,setBusy]=useState(false); return <form className="contact-form" onSubmit={async e => { e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setBusy(true);try{const result=await api('/api/submissions/contact',{method:'POST',body:JSON.stringify(data)});setMessage(`${result.message} کد پیگیری: ${result.id.toLocaleString('fa-IR')}`);form.reset()}catch(error){setMessage(error.message)}finally{setBusy(false)}}}><label>نام<input name="name" required minLength="2" placeholder="نام شما" /></label><label>ایمیل<input name="email" type="email" required placeholder="ایمیل برای پاسخ" /></label><label>پیام<textarea name="message" required minLength="10" rows="4" placeholder="پیام خود را بنویسید" /></label><button disabled={busy}>{busy?'در حال ثبت…':'ثبت پیام'}</button>{message && <p role="status">{message}</p>}</form>; }
function AccountPage({initialMode='login'}) {
  const [mode,setMode]=useState(initialMode);const [form,setForm]=useState({name:'',email:'',password:'',role:'pharmacist'});const [user,setUser]=useState(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  React.useEffect(()=>{api('/api/auth/session').then(x=>{csrfToken=x.csrf;setUser(x.user)}).catch(()=>setMessage('سرویس حساب کاربری در دسترس نیست.'))},[]);
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');try{if(mode==='register'){const result=await api('/api/auth/register',{method:'POST',body:JSON.stringify(form)});setMessage(result.message+' اکنون می‌توانید وارد شوید.');setMode('login')}else{const result=await api('/api/auth/login',{method:'POST',body:JSON.stringify(form)});csrfToken=result.csrf;setUser(result.user);setMessage('با موفقیت وارد شدید.')}}catch(err){setMessage(err.message)}finally{setBusy(false)}};
  const logout=async()=>{try{await apiWrite('/api/auth/logout','POST',{});csrfToken=null;setUser(null);setMessage('از حساب خارج شدید.')}catch(e){setMessage(e.message)}};
  if(user)return <main className="auth-page"><div className="auth-layout"><section className="auth-intro"><Mark /><span>حساب فعال</span><h1>خوش آمدید، {user.name}</h1><p>{user.email} · {user.role}{user.verified?' · تأییدشده':' · در انتظار تأیید مدارک'}</p><a className="button-link" href="/dashboard">رفتن به میز کار</a></section><section className="auth-form-panel"><button onClick={logout}>خروج از حساب</button>{message&&<p role="status">{message}</p>}</section></div></main>;
  return <main className="auth-page"><div className="auth-layout"><section className="auth-intro"><Mark /><span>فضای حرفه‌ای داروسازی</span><h1>{mode==='login'?'ورود به حساب کاربری':'ساخت حساب حرفه‌ای'}</h1><p>{mode==='login'?'برای پیگیری سفارش‌ها، آموزش و فعالیت حرفه‌ای خود وارد شوید.':'یک حساب بسازید تا آموزش و فعالیت حرفه‌ای خود را یک‌جا پیگیری کنید.'}</p><a className="auth-download-link" href="/download">دانلود اپلیکیشن</a></section><section className="auth-form-panel"><div className="account-tabs"><a className={mode==='login'?'selected':''} href="/login">ورود</a><a className={mode==='register'?'selected':''} href="/register">ساخت حساب</a></div><h2>{mode==='login'?'ورود به حساب':'اطلاعات حساب'}</h2><form className="account-form" onSubmit={submit}>{mode==='register'&&<><label>نام و نام خانوادگی<input name="name" value={form.name} onChange={change} autoComplete="name" required minLength="2" /></label><label>نقش حرفه‌ای<select name="role" value={form.role} onChange={change}><option value="pharmacist">داروساز</option><option value="student">دانشجو</option><option value="professor">استاد</option><option value="pharmacy">داروخانه</option><option value="company">شرکت</option><option value="supplier">تأمین‌کننده</option></select></label></>}<label>ایمیل<input type="email" name="email" value={form.email} onChange={change} autoComplete="email" required /></label><label>گذرواژه<input type="password" name="password" value={form.password} onChange={change} autoComplete={mode==='login'?'current-password':'new-password'} minLength="12" required /></label><button disabled={busy}>{busy?'در حال بررسی…':mode==='login'?'ورود امن':'ساخت حساب'}</button></form>{message&&<p role="status">{message}</p>}<p className="form-hint">حساب مدیر از مسیر خصوصی و جداگانه مدیریت می‌شود.</p></section></div></main>;
}
function AboutPanel({ legal = false }) { return <div className="about-copy"><p>{legal ? 'شرایط نهایی استفاده از خدمات، خرید، لغو، محتوای آموزشی و مسئولیت‌های کاربران باید مطابق قوانین محل فعالیت تدوین و به تأیید مالک سامانه برسد.' : 'شکیب لرن برای ساده‌تر کردن دسترسی به دانش و ابزارهای موردنیاز داروسازان شکل گرفته است؛ از یادگیری حرفه‌ای تا خدمات علمی و ارتباط میان جامعهٔ داروسازی.'}</p><p>{legal ? 'پیش از انتشار عمومی، این صفحه باید با متن حقوقی مصوب تکمیل شود. هیچ بند آزمایشی یا تعهد حقوقی ساختگی نمایش داده نمی‌شود.' : 'این نسخه سامانه‌ای مستقل است. دوره‌ها، عکس‌ها، هویت بصری و فایل دریافت اپلیکیشن از دارایی‌های محلی همین پروژه بارگذاری می‌شوند.'}</p><a href="/contact" className="text-link">ارتباط با تیم پروژه <Arrow /></a></div>; }

function Footer() { return <footer className="footer"><div className="wrap footer-main"><div className="footer-brand"><Mark small /><p>درگاه دانش و خدمات تخصصی<br />برای جامعهٔ داروسازی</p></div><div><span>خدمات</span>{sections.slice(0,4).map(s => <a key={s.id} href={s.href}>{s.title}</a>)}<a href="/shortages">گزارش کمبود دارو</a></div><div><span>جامعه</span>{sections.slice(4).map(s => <a key={s.id} href={s.href}>{s.title}</a>)}<a href="/universities">دانشگاه‌ها</a><a href="/shifts">تبادل شیفت</a></div><div><span>شکیب لرن</span><a href="/about">دربارهٔ ما</a><a href="/contact">ارتباط</a><a href="/download">اپلیکیشن</a><a href="/privacy">حریم خصوصی</a><a href="/terms">قوانین استفاده</a></div></div><div className="wrap footer-bottom"><span>© شکیب لرن</span><span>محتوای تخصصی باید منبع روشن و قابل بررسی داشته باشد.</span><a href="/">بازگشت به بالای صفحه</a></div></footer>; }

function NotFound() { return <main className="inner-page"><div className="wrap"><div className="page-intro"><div><div className="eyebrow"><span></span> 404 / مسیر نامعتبر</div><h1>این صفحه پیدا نشد.</h1><p>ممکن است نشانی تغییر کرده باشد. از مسیرهای اصلی سایت ادامه دهید.</p></div></div><div className="library-shortcuts">{sections.map(s=><a key={s.id} href={s.href}>{s.title}<Arrow /></a>)}</div></div></main>; }

const detailKind={drug:'drugs',compound:'compounds',product:'products',course:'courses',event:'events',article:'articles',book:'books',video:'videos',certificate:'certificates'};
function RecordDetail({kind,slug}) {
  const [record,setRecord]=useState(null);const [status,setStatus]=useState('loading');const [message,setMessage]=useState('');const [completed,setCompleted]=useState([]);
  React.useEffect(()=>{let live=true;api(`/api/public/${kind}/${encodeURIComponent(slug)}`).then(x=>{if(live){setRecord(x);setStatus('ready')}}).catch(()=>live&&setStatus('missing'));return()=>{live=false}},[kind,slug]);
  React.useEffect(()=>{if(kind!=='courses'||!record)return;let live=true;api('/api/auth/session').then(async s=>{csrfToken=s.csrf;if(s.user){const p=await api(`/api/courses/${encodeURIComponent(slug)}/progress`);if(live)setCompleted(p.completed||[])}}).catch(()=>{});return()=>{live=false}},[kind,record,slug]);
  const add=()=>{const cart=cartRead();const found=cart.find(x=>x.id===record.id);if(found)found.quantity=Math.min(99,found.quantity+1);else cart.push({id:record.id,slug:record.slug,quantity:1});cartWrite(cart);setMessage('به سبد خرید اضافه شد.')};
  const markChapter=async index=>{const next=completed.includes(index)?completed.filter(x=>x!==index):[...completed,index];try{const result=await apiWrite(`/api/courses/${encodeURIComponent(slug)}/progress`,'PUT',{completed:next});setCompleted(result.completed);setMessage('پیشرفت دوره در حساب شما ذخیره شد.')}catch(e){setMessage(e.message)}};
  if(status==='loading')return <main className="inner-page"><div className="wrap"><div className="loading-line">در حال دریافت محتوا…</div></div></main>;
  if(!record)return <main className="inner-page"><div className="wrap"><div className="page-intro"><div><div className="eyebrow">محتوا در دسترس نیست</div><h1>این مورد منتشر نشده است.</h1><p>ممکن است نشانی تغییر کرده یا رکورد از دسترس خارج شده باشد.</p></div></div><a className="text-link" href="/">بازگشت به صفحهٔ اصلی</a></div></main>;
  const chapters=Array.isArray(record.body?.chapters)?record.body.chapters:[];
  const gallery=Array.isArray(record.body?.gallery)?record.body.gallery:[];
  const listPath=kind==='drugs'?'/drugs':kind==='products'?'/market':kind==='courses'?'/learn':kind==='events'?'/events':'/library';
  return <main className="inner-page"><div className="wrap"><div className="crumb"><a href="/">خانه</a> / <a href={listPath}>بازگشت به فهرست</a></div><article className="detail-view">
    <div className="detail-heading"><div><div className="eyebrow">{record.category||record.kind}</div><h1>{record.title}</h1>{record.summary&&<p>{record.summary}</p>}</div>{record.imageUrl&&<img className={kind==='courses'?'course-cover':''} src={record.imageUrl} alt={record.title}/>}</div>
    {kind==='drugs'&&<div className="medical-notice">اطلاعات دارویی برای آگاهی حرفه‌ای است و جایگزین قضاوت بالینی، بروشور مصوب یا نظر متخصص نیست.</div>}
    {record.sourceUrl&&kind!=='courses'&&<p className="source-credit">منبع: <a href={record.sourceUrl} target="_blank" rel="noreferrer">مشاهدهٔ مرجع اصلی</a></p>}
    {kind==='courses'&&<section className="course-enrollment"><div><strong>{coursePriceLabel(record.body)}</strong><span>ثبت درخواست در همین سامانه</span></div><RecordAction record={record} kind="courses"/></section>}
    {record.body?.content&&<div className="article-body">{String(record.body.content).split('\n').filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</div>}
    {gallery.length>0&&<section className="course-gallery" aria-label="تصاویر دوره"><h2>تصاویر دوره</h2><div>{gallery.map((image,i)=><figure key={`${image.src}-${i}`}><img src={image.src} alt={image.alt||record.title} loading="lazy"/><figcaption>{image.alt||record.title}</figcaption></figure>)}</div></section>}
    {kind==='products'&&<div className="detail-purchase"><strong>{record.price?.toLocaleString('fa-IR')} تومان</strong><span>موجودی: {record.stock?.toLocaleString('fa-IR')}</span><button disabled={!record.stock} onClick={add}>افزودن به سبد</button>{message&&<small role="status">{message}</small>}</div>}
    {kind==='events'&&<RecordAction record={record} kind="events"/>}{kind==='jobs'&&<RecordAction record={record} kind="jobs"/>}
    {kind==='courses'&&chapters.length>0&&<div className="course-outline"><h2>فصل‌های دوره · {completed.length.toLocaleString('fa-IR')} از {chapters.length.toLocaleString('fa-IR')} تکمیل‌شده</h2>{chapters.map((c,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{c.title||`فصل ${i+1}`}</strong>{c.summary&&<p>{c.summary}</p>}{c.videoUrl&&<a href={c.videoUrl} target="_blank" rel="noreferrer">مشاهدهٔ ویدیو</a>}<button className="chapter-complete" onClick={()=>markChapter(i)}>{completed.includes(i)?'تکمیل‌شده':'علامت‌گذاری به‌عنوان تکمیل'}</button></div></article>)}{message&&<p role="status">{message}</p>}</div>}
    {!record.summary&&!record.body?.content&&kind!=='products'&&kind!=='courses'&&<EmptyState title="جزئیات تکمیلی موجود نیست" description="برای این محتوا فقط اطلاعاتی که در مدیریت ثبت و منتشر شده نمایش داده می‌شود."/>}
  </article></div></main>;
}

function App() {
  const path = useMemo(() => decodeURI(window.location.pathname.replace(/\/$/, '') || '/'), []);
  const detail=path.match(/^\/(drug|compound|product|course|event|article|book|video|certificate)\/([^/]+)$/);
  const detailTitles={drug:'دارونامه',compound:'فرمول ترکیبی',product:'محصول',course:'دوره آموزشی',event:'رویداد',article:'مقاله',book:'کتاب',video:'ویدیوی آموزشی',certificate:'گواهی‌نامه'};
  const [theme, setTheme] = useState(() => localStorage.getItem('daro-theme') || 'light');
  React.useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.dataset.route = path; localStorage.setItem('daro-theme', theme); }, [theme, path]);
  React.useEffect(() => { if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{}); }, []);
  React.useEffect(() => {
  const info = path === '/' ? ['آموزش تخصصی داروسازی و فرمولاسیون | شکیب‌لرن | شکیب‌ لرن', 'درگاه تخصصی داروسازی؛ دارونامه، آموزش، بازار حرفه‌ای، رویداد و کاریابی.'] : routeTitles[path] ? [`${routeTitles[path][1]} | شکیب لرن`, routeTitles[path][2]] : detail ? [`${detailTitles[detail[1]]} | شکیب لرن`, `مشاهدهٔ اطلاعات و جزئیات ${detailTitles[detail[1]]} در شکیب لرن.`] : ['صفحه پیدا نشد | شکیب لرن', 'مسیر درخواستی در شکیب لرن وجود ندارد.'];
    document.title = info[0];
    let description = document.querySelector('meta[name="description"]'); if (!description) { description=document.createElement('meta');description.name='description';document.head.append(description); } description.content=info[1];
    let canonical = document.querySelector('link[rel="canonical"]'); if (!canonical) { canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical); } canonical.href = `${window.location.origin}${path}`;
    let schema = document.getElementById('site-schema'); if (!schema) { schema=document.createElement('script');schema.id='site-schema';schema.type='application/ld+json';document.head.append(schema); }
    schema.textContent = JSON.stringify({ '@context':'https://schema.org', '@type':'WebSite', name:'شکیب لرن', inLanguage:'fa-IR', url:window.location.origin+'/', description:info[1], potentialAction:{ '@type':'SearchAction', target:`${window.location.origin}/search?q={search_term_string}`, 'query-input':'required name=search_term_string' } });
  }, [path]);
  const known = path === '/' || routeTitles[path] || sections.some(s=>s.href===path) || path.startsWith('/admin/');
  const page = detail ? <RecordDetail kind={detailKind[detail[1]]} slug={decodeURIComponent(detail[2])}/> : path === '/' ? <Home /> : ['/account','/login','/register'].includes(path) ? <AccountPage initialMode={path === '/register' ? 'register' : 'login'} /> : known ? <DirectoryPage path={path} /> : <NotFound />;
  return <><Header path={path} theme={theme} onTheme={()=>setTheme(theme==='dark'?'light':'dark')} />{page}<Footer /></>;
}

createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
