import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const A='/assets/images/';
const products=[
 {title:'دارو درمانی در اختلالات شایع اورژانس',price:'۲۸۰,۰۰۰',img:'asset-2.webp',path:'/product/emergency/'},
 {title:'کم خونی و داروهای موجود در داروخانه',price:'۳۳۰,۰۰۰',img:'asset-3.webp',path:'/product/anemia/'},
 {title:'مکمل های غذایی دارویی و ورزشی',price:'۵۰۰,۰۰۰',img:'asset-4.webp',path:'/product/suppelements/'},
 {title:'OTC Therapy بیماری های چشم و درمان آن',price:'۵۲۰,۰۰۰',img:'asset-1.webp',path:'/product/otc-therapy/'},
];
const posts=[
 {title:'آیا قاعدگی بر زیبایی پوست و مو تاثیری دارد؟',text:'دوره ی پریود و یکی دو روز پیش از آن، زمانیست که پوست شما درگیر مشکلات مرتبط با پریودی نظیر جوش، لک و...',date:'۲۸ ژانویه',img:'asset-5.webp'},
 {title:'نکاتی برای مراقبت از پوست در فصل‌های مختلف',text:'بدون شک پوست یکی از مهم‌ترین فاکتورهای ارزیابی زیبایی افراد، به خصوص خانم‌ها به حساب می‌آید. عوامل مختلفی...',date:'۲۸ ژانویه',img:'asset-3.webp'},
 {title:'اهمیت کم خوابی بر سلامت پوست و مو',text:'تاثیر خواب بر سلامت پوست و مو اهمیت کم خوابی بر پوست بسیار زیاد است. خواب خوب تاثیر بسزایی بر روی شا...',date:'۲۸ ژانویه',img:'asset-4.webp'},
 {title:'بررسی علت ترک پا و نحوه درمان آن با بهترین کرم‌ها',text:'صابون و تمیزکننده‌های نامناسب همان‌طور که احتمالا می‌دانید استفاده مداوم از صابون، به خصوص صابون‌ها...',date:'۲۶ ژانویه',img:'asset-1.webp'},
];
const nav=[['خانه','/'],['فروشگاه','/shop/'],['مقالات','#'],['دوره‌ها','#'],['جزوات','#'],['تماس با ما','/contact-us/']];
function Header({onMenu,onCart}){return <><div className="top"><span>آموزش تخصصی داروسازی و فرمولاسیون</span><span>کانال تلگرام　 اینستاگرام　 تماس با ما</span></div><header><button className="hamb" onClick={onMenu}>☰ <small>منو</small></button><a href="/" className="brand"><img src={A+'asset-0.webp'}/><span>شکیب‌لرن</span></a><nav>{nav.map(([n,p])=><a href={p} key={n}>{n}{(n==='مقالات'||n==='دوره‌ها'||n==='جزوات')&&<i>⌄</i>}</a>)}</nav><div className="actions"><a href="/my-account/" title="حساب کاربری">♙</a><button onClick={onCart}>🛒 <b>0</b></button></div></header></>}
function ProductCard({p}){return <article className="product"><div className="pimg"><img src={A+p.img}/><span className="heart">♡</span></div><h3><a href={p.path}>{p.title}</a></h3><div className="price">{p.price} <small>تومان</small></div><button className="add">افزودن به سبد خرید　＋</button></article>}
function Footer(){return <footer><div><h4>دانلود اپلیکیشن:</h4><a>▣　مستقیم اندروید</a><a>▣　گوگل پلی</a><a>　سیب اپ</a><a>　سیبچه</a></div><div><h4>تماس با ما:</h4><a>کانال تلگرام</a><a>اینستاگرام</a><a>تلگرام مدیریت</a><a>واتساپ مدیریت</a><a>۰۹۱۳۵۸۹۶۳۵۴</a></div><div><h4>دوره‌ها</h4><a>همه</a><a>بالینی</a><a>فارماسیوتیکس</a><a>آرایشی و بهداشتی</a><a>فارماکوگنوزی</a></div><div><h4>مقالات</h4><a>۲۰۲۴</a><a>۲۰۲۳</a><a>۲۰۲۲</a><a>۲۰۲۱</a><a>۲۰۲۱ و قبل</a></div><div className="copy">تمام حقوق برای <b>شکیب‌لرن</b> محفوظ است.</div></footer>}
function Home(){const [tab,setTab]=useState('همه'); return <><section className="hero"><div className="hero-copy"><span className="eyebrow">دوره ویژه</span><h1>درحال برگزاری</h1><h2>مدرسه پاییزه فرمولاسیون‌های ترکیبی</h2><p>آموزش جامع و کاربردی ساخت داروهای ترکیبی با حضور اساتید مطرح داروسازی</p><div><strong>۱۱,۵۵۰,۰۰۰ تومان</strong><del>۳۴,۶۵۰,۰۰۰ تومان</del></div><a className="primary" href="/product/autumn-compounding-school/">انتخاب گزینه‌ها　→</a></div><img src={A+'asset-1.webp'}/><div className="dots">● ○ ○ ○ ○ ○</div></section><section className="section"><div className="section-head"><h2>پر فروش ترین</h2><a href="/shop/">مشاهده همه　→</a></div><div className="feature"><img src={A+'asset-2.webp'}/><div><span className="badge">-۱۳٪ ویژه</span><h2>مسترکلاس ساخت داروهای ترکیبی</h2><p><del>قیمت اصلی ۴,۵۰۰,۰۰۰ تومان بود.</del> قیمت فعلی <b>۳,۹۰۰,۰۰۰ تومان</b> است.</p><button className="primary">افزودن به سبد خرید　＋</button></div></div></section><section className="section pale"><div className="section-head"><h2>دوره‌ها</h2></div><div className="tabs">{['بالینی','فارماسیوتیکس','فارماکوگنوزی','همه'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="grid">{products.map(p=><ProductCard key={p.title} p={p}/>)}</div></section><section className="section"><div className="section-head"><h2>آخرین مقالات</h2><a href="/mag/">همه مقالات　→</a></div><div className="grid posts">{posts.map(p=><article className="post" key={p.title}><img src={A+p.img}/><small>{p.date}</small><h3>{p.title}</h3><p>{p.text}</p><a>ادامه مطلب　→</a></article>)}</div></section></>}
function Shop(){return <Page title="فروشگاه"><div className="shopbar"><b>دوره‌های آموزشی</b><button>مرتب‌سازی بر اساس جدیدترین</button></div><div className="grid">{products.concat(products).map((p,i)=><ProductCard key={i} p={p}/>)}</div></Page>}
function Page({title,children}){return <><div className="page-title"><span>خانه　/　</span>{title}<h1>{title}</h1></div><main className="section page">{children}</main></>}
function ProductPage({title}){return <Page title={title}><div className="detail"><img src={A+'asset-2.webp'}/><div><span className="badge">ویژه جدید</span><h2>{title}</h2><p>این دوره با هدف آموزش عملی و تخصصی داروسازی تهیه شده است. محتوای دوره برای دانشجویان و داروسازان طراحی شده است.</p><strong className="bigprice">۳۹۰,۰۰۰ تومان</strong><button className="primary">افزودن به سبد خرید　＋</button></div></div><div className="accordion"><details open><summary>توضیحات دوره</summary><p>در این دوره با اصول و روش‌های کاربردی آشنا می‌شوید و به محتوای آموزشی دسترسی خواهید داشت.</p></details><details><summary>سرفصل‌ها</summary><p>مبانی داروشناسی، فرمولاسیون و کاربردهای بالینی.</p></details></div></Page>}
function Blog(){return <Page title="مقالات"><div className="grid posts">{posts.concat(posts).map((p,i)=><article className="post" key={i}><img src={A+p.img}/><small>{p.date}</small><h3>{p.title}</h3><p>{p.text}</p><a>ادامه مطلب　→</a></article>)}</div></Page>}
function Contact(){return <Page title="تماس با ما"><div className="contact"><div><h2>با ما در ارتباط باشید</h2><p>برای ارتباط با تیم شکیب‌لرن می‌توانید از راه‌های زیر استفاده کنید.</p><p>تلفن: ۰۹۱۳۵۸۹۶۳۵۴</p><p>ایمیل: info@shakiblearn.com</p></div><form><label>نام شما<input placeholder="نام و نام خانوادگی"/></label><label>ایمیل<input placeholder="ایمیل"/></label><label>پیام<textarea rows="5" placeholder="پیام شما"></textarea></label><button className="primary">ارسال پیام</button></form></div></Page>}
function Utility({title,children}){return <Page title={title}><div className="utility"><h2>{title}</h2><p>{children}</p></div></Page>}
function App(){const [menu,setMenu]=useState(false),[cart,setCart]=useState(false);let path=location.pathname;let content=path==='/shop/'?<Shop/>:path==='/mag/'?<Blog/>:path==='/contact-us/'?<Contact/>:path==='/application/'?<Utility title="دانلود اپلیکیشن">اپلیکیشن شکیب‌لرن را برای دسترسی سریع‌تر به دوره‌ها دریافت کنید.</Utility>:path==='/my-account/'?<Utility title="ورود / ثبت نام">برای استفاده از امکانات حساب کاربری وارد شوید یا حساب جدید ایجاد کنید.</Utility>:path==='/cart/'?<Utility title="سبد خرید">هیچ محصولی در سبد خرید نیست.</Utility>:path.includes('/product/')?<ProductPage title={path.includes('anemia')?'کم خونی و داروهای موجود در داروخانه':path.includes('emergency')?'دارو درمانی در اختلالات شایع اورژانس':path.includes('suppelements')?'مکمل های غذایی دارویی و ورزشی':path.includes('otc')?'OTC Therapy بیماری های چشم و درمان آن':path.includes('autumn')?'مدرسه پاییزه فرمولاسیون‌های ترکیبی':'مسترکلاس ساخت داروهای ترکیبی'}/>:<Home/>;return <><Header onMenu={()=>setMenu(true)} onCart={()=>setCart(true)}/>{content}<Footer/><div className={'drawer '+(menu?'open':'')}><button onClick={()=>setMenu(false)}>×</button><img src={A+'asset-0.webp'}/>{nav.map(([n,p])=><a href={p} key={n}>{n}</a>)}</div><div className={'cart-drawer '+(cart?'open':'')}><button onClick={()=>setCart(false)}>×</button><h2>سبد خرید</h2><p>هیچ محصولی در سبد خرید نیست.</p><a className="primary" href="/shop/">بازگشت به فروشگاه</a></div><div className="bottom"><a href="/shop/">فروشگاه</a><a href="/application/">دانلود اپلیکیشن</a><a onClick={()=>setCart(true)}>سبد خرید (۰)</a><a href="/my-account/">حساب کاربری</a></div></>}
createRoot(document.getElementById('root')).render(<App/>);
